export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';
export const RESULTS_LOADING = 'RESULTS_LOADING';
export const RESULTS_FETCHED = 'RESULTS_FETCHED';
export const RESULTS_ERROR = 'RESULTS_ERROR';